# Generated by Django 4.1.7 on 2023-02-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('color', models.CharField(max_length=55)),
                ('breed', models.CharField(max_length=55)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.CharField(max_length=512, verbose_name='URL')),
                ('booking', models.BooleanField(default=False)),
                ('full_price', models.PositiveIntegerField()),
            ],
        ),
    ]
