# Generated by Django 4.1.7 on 2023-02-15 18:12

from django.db import migrations


def create_data(apps, schema_editor):
    Cat = apps.get_model('booking', 'cat')
    Cat(name="Рыжий", color="Рыжый", breed="Сомалийская кошка", age=5, photo='media/photo/cat.jpeg',
        full_price=300).save()
    Cat(name="Пыжик", color="ЧЧерный", breed="Сингапура", age=2, photo='media/photo/cat.jpeg', full_price=120).save()
    Cat(name="Бегемотик", color="Красный", breed="Манчкин", age=7, photo='media/photo/cat.jpeg',
        full_price=240).save()
    Cat(name="Карлсон", color="Бело-белый", breed="Норвежская лесная", age=9, photo='media/photo/cat.jpeg',
        full_price=500).save()


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
